[package]
name = "bms-database"
version.workspace = true
edition.workspace = true

[dependencies]
bms-model.workspace = true
bms-rule.workspace = true
anyhow.workspace = true
chrono.workspace = true
flate2.workspace = true
rand.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile.workspace = true
