[package]
name = "bms-database"
version.workspace = true
edition.workspace = true

[dependencies]
bms-model.workspace = true
anyhow.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
