[package]
name = "bms-launcher"
version.workspace = true
edition.workspace = true

[dependencies]
bms-config.workspace = true
anyhow.workspace = true
eframe.workspace = true
egui.workspace = true
rfd.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
