[package]
name = "bms-ir"
version.workspace = true
edition.workspace = true

[dependencies]
bms-model.workspace = true
bms-rule = { workspace = true }
bms-replay = { workspace = true }
bms-database = { workspace = true }
anyhow.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
encoding_rs.workspace = true
sha2.workspace = true
quick-xml = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
wiremock = { workspace = true }
