[package]
name = "bms-ir"
version.workspace = true
edition.workspace = true

[dependencies]
bms-model.workspace = true
anyhow.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
