[package]
name = "bms-stream"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
tokio = { workspace = true, features = ["sync", "io-util", "net", "time"] }
serde.workspace = true
tracing.workspace = true
