[package]
name = "bms-external"
version.workspace = true
edition.workspace = true

[dependencies]
bms-config.workspace = true
bms-database.workspace = true
bms-rule.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tokio-tungstenite.workspace = true
sha2.workspace = true
base64.workspace = true
image.workspace = true
reqwest.workspace = true
chrono.workspace = true
tracing.workspace = true
rusqlite.workspace = true

[dev-dependencies]
tempfile.workspace = true
